/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as AboutImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as authVerifyImport } from './routes/(auth)/verify'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AppCompaniesNewImport } from './routes/app/companies/new'
import { Route as AppCompaniesCompanySlugRouteImport } from './routes/app/companies/$companySlug/route'
import { Route as AppCompaniesCompanySlugIndexImport } from './routes/app/companies/$companySlug/index'
import { Route as AppCompaniesCompanySlugTimelineImport } from './routes/app/companies/$companySlug/timeline'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authVerifyRoute = authVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => authRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AppCompaniesNewRoute = AppCompaniesNewImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCompaniesCompanySlugRouteRoute =
  AppCompaniesCompanySlugRouteImport.update({
    id: '/companies/$companySlug',
    path: '/companies/$companySlug',
    getParentRoute: () => AppRouteRoute,
  } as any)

const AppCompaniesCompanySlugIndexRoute =
  AppCompaniesCompanySlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCompaniesCompanySlugRouteRoute,
  } as any)

const AppCompaniesCompanySlugTimelineRoute =
  AppCompaniesCompanySlugTimelineImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppCompaniesCompanySlugRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyImport
      parentRoute: typeof authRouteImport
    }
    '/app/companies/$companySlug': {
      id: '/app/companies/$companySlug'
      path: '/companies/$companySlug'
      fullPath: '/app/companies/$companySlug'
      preLoaderRoute: typeof AppCompaniesCompanySlugRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/companies/new': {
      id: '/app/companies/new'
      path: '/companies/new'
      fullPath: '/app/companies/new'
      preLoaderRoute: typeof AppCompaniesNewImport
      parentRoute: typeof AppRouteImport
    }
    '/app/companies/$companySlug/timeline': {
      id: '/app/companies/$companySlug/timeline'
      path: '/timeline'
      fullPath: '/app/companies/$companySlug/timeline'
      preLoaderRoute: typeof AppCompaniesCompanySlugTimelineImport
      parentRoute: typeof AppCompaniesCompanySlugRouteImport
    }
    '/app/companies/$companySlug/': {
      id: '/app/companies/$companySlug/'
      path: '/'
      fullPath: '/app/companies/$companySlug/'
      preLoaderRoute: typeof AppCompaniesCompanySlugIndexImport
      parentRoute: typeof AppCompaniesCompanySlugRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyRoute: typeof authVerifyRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyRoute: authVerifyRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppCompaniesCompanySlugRouteRouteChildren {
  AppCompaniesCompanySlugTimelineRoute: typeof AppCompaniesCompanySlugTimelineRoute
  AppCompaniesCompanySlugIndexRoute: typeof AppCompaniesCompanySlugIndexRoute
}

const AppCompaniesCompanySlugRouteRouteChildren: AppCompaniesCompanySlugRouteRouteChildren =
  {
    AppCompaniesCompanySlugTimelineRoute: AppCompaniesCompanySlugTimelineRoute,
    AppCompaniesCompanySlugIndexRoute: AppCompaniesCompanySlugIndexRoute,
  }

const AppCompaniesCompanySlugRouteRouteWithChildren =
  AppCompaniesCompanySlugRouteRoute._addFileChildren(
    AppCompaniesCompanySlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppCompaniesCompanySlugRouteRoute: typeof AppCompaniesCompanySlugRouteRouteWithChildren
  AppCompaniesNewRoute: typeof AppCompaniesNewRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompaniesCompanySlugRouteRoute:
    AppCompaniesCompanySlugRouteRouteWithChildren,
  AppCompaniesNewRoute: AppCompaniesNewRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/app/companies/$companySlug': typeof AppCompaniesCompanySlugRouteRouteWithChildren
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/companies/$companySlug/timeline': typeof AppCompaniesCompanySlugTimelineRoute
  '/app/companies/$companySlug/': typeof AppCompaniesCompanySlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/companies/$companySlug/timeline': typeof AppCompaniesCompanySlugTimelineRoute
  '/app/companies/$companySlug': typeof AppCompaniesCompanySlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/app/companies/$companySlug': typeof AppCompaniesCompanySlugRouteRouteWithChildren
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/companies/$companySlug/timeline': typeof AppCompaniesCompanySlugTimelineRoute
  '/app/companies/$companySlug/': typeof AppCompaniesCompanySlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/onboarding'
    | '/login'
    | '/register'
    | '/verify'
    | '/app/companies/$companySlug'
    | '/app/companies/new'
    | '/app/companies/$companySlug/timeline'
    | '/app/companies/$companySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/about'
    | '/onboarding'
    | '/login'
    | '/register'
    | '/verify'
    | '/app/companies/new'
    | '/app/companies/$companySlug/timeline'
    | '/app/companies/$companySlug'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/about'
    | '/onboarding'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/verify'
    | '/app/companies/$companySlug'
    | '/app/companies/new'
    | '/app/companies/$companySlug/timeline'
    | '/app/companies/$companySlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  OnboardingRoute: typeof OnboardingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  OnboardingRoute: OnboardingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/app",
        "/about",
        "/onboarding"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/verify"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/companies/$companySlug",
        "/app/companies/new"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/verify": {
      "filePath": "(auth)/verify.tsx",
      "parent": "/(auth)"
    },
    "/app/companies/$companySlug": {
      "filePath": "app/companies/$companySlug/route.tsx",
      "parent": "/app",
      "children": [
        "/app/companies/$companySlug/timeline",
        "/app/companies/$companySlug/"
      ]
    },
    "/app/companies/new": {
      "filePath": "app/companies/new.tsx",
      "parent": "/app"
    },
    "/app/companies/$companySlug/timeline": {
      "filePath": "app/companies/$companySlug/timeline.tsx",
      "parent": "/app/companies/$companySlug"
    },
    "/app/companies/$companySlug/": {
      "filePath": "app/companies/$companySlug/index.tsx",
      "parent": "/app/companies/$companySlug"
    }
  }
}
ROUTE_MANIFEST_END */
